name: Deploy Book

on:
  push:
    branches:
    - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Rust
      uses: raftario/setup-rust-action@v1
      with:
        rust-channel: stable
        rust-host: x86_64-unknown-linux-gnu

    - name: Install mdBook
      run: |
        cargo install mdbook

    - name: Build the book
        mdbook build

    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./book
